### PR TITLE
Add programIdOverride

### PR DESCRIPTION
**Pull request by kklas**
Added
```
// Use this only if you need to change the program ID dynamically during app runtime.
export const programIdOverride: (() => PublicKey) | undefined = undefined
```
to `programId.ts`. 

When `programIdOverride` function is defined, it will be called and used to override the program ID defined statically with the `PROGRAM_ID` constant.

### CODE REVIEW

**Comment by ronanyeah** [comment]
Does this mean that the logic to choose the URL, and the URL values, need to be inside the `programId.ts` file?

It would make more sense to me if the override function accepted a `PublicKey` argument and my application code called it.

**Comment by kklas** [comment]
Not sure what you mean by `URL`, this is a way to override the program ID.

The logic to choose the programId doesn't have to live inside `programId.ts`. You can also do:
```
// programId.ts

import { getFooProgramId } from '...'

...

export const programIdOverride: (() => PublicKey) | undefined = getFooProgramId
```

I wanted to avoid introducing programId as an arg to functions because changing programIds dynamically during apps runtime is a niche use case that you'd only rarely need (there should be only one programId for a smart contract so why would you ever need to change this dynamically?). I want to keep the API as simple as possible and having programId as an arg would confuse things since there is PROGRAM_ID constant that should be the source of truth.

I'm still not convinced that this is even needed btw. Can you give me a concrete example of a use case for changing programIds dynamically?

**Comment by ronanyeah** [comment]
Oops, I meant `PublicKey` not `URL`.

> Can you give me a concrete example of a use case for changing programIds dynamically?

Same code on different chains w/ different program ids. #51 seems active with similar minded users.

> Perhaps you could argue that the program ids should always be passed in dynamically

Yes please. I think this:
`const programId = (programIdOverride && programIdOverride()) || PROGRAM_ID`

would be better as:

`const programId = getProgramId()`

**Comment by kklas** [comment]
> Same code on different chains w/ different program ids

WDYM different chains? Are there any other chains that support the Solana runtime or are you referring to devnet / mainnet?
If the latter then my answer is that there is never a reason to call devnet in a production app.
And you need to run against devnet in you dev environment then you can do e.g. `export const PROGRAM_ID: PublicKey = new PublicKey(process.env.REACT_APP_MY_PROGRAM_ID)`.

>Yes please. I think this (...) would be better as (...)

But again, what is the use case here? Almost always you need static. Why would you ever need dynamic in a production app? I don't see what is the problem here.

**Comment by ronanyeah** [comment]
> are you referring to devnet / mainnet?
Yes.

I don't really have anything more to add. I would find it useful. Kind of surprised this PR exists if you feel it is against the ideals of the library.

**Comment by kklas** [comment]
Fair enough. Closing the PR. Static program ids are simple and safe. I'm open to revisiting this if somebody can explain a concrete use case.

**Comment by ronanyeah** [comment]
Would still like to see these concerns addressed, which I think are created/exacerbated by the existence of a static id.
> I like the idea of generated code being a deterministic dependency of a project. So the generation command is the only thing that is required when onboarding new team members. At the moment I'm gonna have to document the various subtleties of how programId.ts behaves, what it does/doesn't overwrite, and have instructions to git revert / don't commit programId.ts changes etc.
https://github.com/kklas/anchor-client-gen/issues/51#issuecomment-1189510478

**Comment by kklas** [comment]
> So the generation command is the only thing that is required when onboarding new team members

The generation command should be used only when there are changes to the program (not on onboarding since the generated code should be included in the repo). But even if you do run the generation command, user defined constants in `programId.ts` shouldn't get overwritten (unless there's a bug).

So I don't see what is the issue exactly?

**Comment by ronanyeah** [comment]
I don't like that application specific logic (names of env vars, importing `getFooProgramId` like suggested above) is being mixed in with a file that is _sometimes_ edited by the codegen process. I would rather the separations were cleaner. I think the colloquial term is 'leaky abstraction'.

**Comment by kklas** [comment]
The `programId.ts` is idempotent and it won't change on subsequent generation runs. Can you describe a concrete issue you are running into with this or expect to run into?

**Comment by y2kappa** [comment]
Surprised this PR got closed. The usecase is pretty simple and happens on several of our apps/uis - you have different programIDs for devnet and mainnet, you don't want to codegen different folders because it's identical IDL, you need to be able to change the program ID. How do you solve this otherwise? I think the solution was pretty good.

**Pull request closed without merging**
